PR:  gh#149 : Adding changes for menu driven gtest tests
rdkcentral/ut-core pull request #150
Opened 2024-11-27 17:04 UTC by kanjoe24

Changes for menu driven gtest tests

2024-12-03 16:00 UTC, Ulrond requested changes
minor change

2024-12-03 16:00 UTC, Ulrond commented on src/cpp_source/ut_gtest.cpp
> +#define _(x) x
think you should call this something more sensible, rather than just `_`

2024-12-04 11:34 UTC, Ulrond approved these changes
looks good, but can we have a demo before we merge.

2024-12-04 14:29 UTC, kanjoe24 commented
results for ut-core release script:

```shell
./release-test-script-ut-core.sh -t feature/gh149-menu-system-cpp-test
UT_CORE_BRANCH_NAME = feature/gh149-menu-system-cpp-test
UT_CONTROL_BRANCH_NAME = 
UT_CONTROL_BRANCH_NAME is empty
==========================================================
RESULTS for ubuntu 
On the branch feature/gh149-menu-system-cpp-test
. PASS
framework/ut-control/build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
build/linux/cpp_libs/lib/libgtest.a exists. PASS
build/linux/cpp_libs/lib/libgtest_main.a exists. PASS
==========================================================
==========================================================
RESULTS for VM-SYNC 
On the branch feature/gh149-menu-system-cpp-test
. PASS
framework/ut-control/build/linux/curl/lib/libcurl.a exists. PASS
framework/ut-control/build/linux/openssl/lib/libssl.a exists. PASS 
framework/ut-control/host-tools/CMake-3.30.0/build/bin/cmake exists. PASS 
build/linux/cpp_libs/lib/libgtest.a exists. PASS
build/linux/cpp_libs/lib/libgtest_main.a exists. PASS
==========================================================
==========================================================
RESULTS for dunfell_arm 
On the branch feature/gh149-menu-system-cpp-test
. PASS
framework/ut-control/build/arm/curl/lib/libcurl.a exists. PASS
framework/ut-control/build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
build/arm/cpp_libs/lib/libgtest.a exists. PASS
build/arm/cpp_libs/lib/libgtest_main.a exists. PASS
==========================================================
==========================================================
RESULTS for dunfell_linux 
On the branch feature/gh149-menu-system-cpp-test
. PASS
framework/ut-control/build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
build/linux/cpp_libs/lib/libgtest.a exists. PASS
build/linux/cpp_libs/lib/libgtest_main.a exists. PASS
==========================================================
==========================================================
RESULTS for kirkstone_arm 
On the branch feature/gh149-menu-system-cpp-test
. PASS
framework/ut-control/build/arm/curl/lib/libcurl.a exists. PASS
framework/ut-control/build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
build/arm/cpp_libs/lib/libgtest.a exists. PASS
build/arm/cpp_libs/lib/libgtest_main.a exists. PASS
==========================================================
==========================================================
RESULTS for kirkstone_linux 
On the branch feature/gh149-menu-system-cpp-test
. PASS
framework/ut-control/build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
build/linux/cpp_libs/lib/libgtest.a exists. PASS
build/linux/cpp_libs/lib/libgtest_main.a exists. PASS
==========================================================

```  

Results for platform release script with commands ./build_ut.sh for linux and ./build_ut.sh TARGET=arm for arm

```shell
./release-test-script-platform.sh -t feature/gh149-menu-system-cpp-test
UT_CORE_BRANCH_NAME = feature/gh149-menu-system-cpp-test
UT_CONTROL_BRANCH_NAME = 
UT_CONTROL_BRANCH_NAME is empty
==========================================================
RESULTS for ubuntu 
On the branch feature/gh149-menu-system-cpp-test
            . PASS
/home/jpn323/workspace/gh149-menu-system-cpp-test/scripts/rdk-halif-hdmi_cec-ubuntu
ut/bin/hal_test exists. PASS
ut/ut-core/framework/ut-control/build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for VM-SYNC 
On the branch feature/gh149-menu-system-cpp-test
            . PASS
/home/jpn323/workspace/gh149-menu-system-cpp-test/scripts/rdk-halif-hdmi_cec-VM-SYNC
ut/bin/hal_test exists. PASS
ut/ut-core/framework/ut-control/build/linux/curl/lib/libcurl.a exists. PASS
ut/ut-core/framework/ut-control/build/linux/openssl/lib/libssl.a exists. PASS 
ut/ut-core/framework/ut-control/host-tools/CMake-3.30.0/build/bin/cmake exists. PASS 
==========================================================
==========================================================
RESULTS for dunfell_arm 
On the branch feature/gh149-menu-system-cpp-test
            . PASS
/home/jpn323/workspace/gh149-menu-system-cpp-test/scripts/rdk-halif-hdmi_cec-dunfell_arm
ut/bin/hal_test exists. PASS
ut/ut-core/framework/ut-control/build/arm/curl/lib/libcurl.a exists. PASS
ut/ut-core/framework/ut-control/build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for dunfell_linux 
On the branch feature/gh149-menu-system-cpp-test
            . PASS
/home/jpn323/workspace/gh149-menu-system-cpp-test/scripts/rdk-halif-hdmi_cec-dunfell_linux
ut/bin/hal_test exists. PASS
CURL static lib does not exist. PASS 
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for kirkstone_arm 
On the branch feature/gh149-menu-system-cpp-test
            . PASS
/home/jpn323/workspace/gh149-menu-system-cpp-test/scripts/rdk-halif-hdmi_cec-kirkstone_arm
ut/bin/hal_test exists. PASS
ut/ut-core/framework/ut-control/build/arm/curl/lib/libcurl.a exists. PASS
ut/ut-core/framework/ut-control/build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for kirkstone_linux 
On the branch feature/gh149-menu-system-cpp-test
            . PASS
/home/jpn323/workspace/gh149-menu-system-cpp-test/scripts/rdk-halif-hdmi_cec-kirkstone_linux
ut/bin/hal_test exists. PASS
ut/ut-core/framework/ut-control/build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================
jpn323@janus ~/workspace/gh149-menu-system-cpp-test/scripts (feature/gh149-menu-system-cpp-test)$ 

```

2024-12-05 10:01 UTC, Ulrond approved these changes
go for it

2024-12-05 10:08 UTC, merged